name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH key
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" | tr -d '\r' > my-key.pem
          chmod 400 my-key.pem

      - name: Verify SSH key creation
        run: ls -l my-key.pem

      - name: Deploy to EC2
        run: |
          ssh -vvv -i my-key.pem -o StrictHostKeyChecking=no ubuntu@ec2-43-203-19-143.ap-northeast-2.compute.amazonaws.com 'cd Blog && git pull origin main && yarn install && yarn build && pm2 restart all'
